### ISSUE TITLE
README Screenshot and how to link my site

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/ecommerce-pattern-library#2]
Hi Thomas, this is the screenshot of my README pages
Question is how to link my page here, you mentioned is not linked yet.

And to be honest and need to confess I am lost in Web Dev right now, with all going on in my personal life and around us all. I will try my best but today I just felt completely lost in what you were showing other people. 
I have TONs of questions ahaha but I will try to figure some out first and ask later.

<img width="1082" alt="Screen Shot 2020-03-24 at 2 47 49 PM" src="https://user-images.githubusercontent.com/43067752/77465117-8af99080-6dde-11ea-8902-78ff5f26439b.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
The readme is missing a bunch of information:

- Project title
- Project introduction & brand
- Links to your UX, etc

**Comment by thomasjbradley** [comment]
The link I need is the Netflify link to your live ecommerce website. If you sign in here, you should see a URL: https://www.netlify.com/

Then paste that into your GitHub repo, shown in the screenshot.

![Screen Shot 2020-03-24 at 3 30 15 PM](https://user-images.githubusercontent.com/105192/77468741-66081c00-6de4-11ea-8418-d10bff4d288b.png)

**Comment by dasi0075** [comment]
I did it a while back would be this one? @thomasjbradley 

<img width="1207" alt="Screen Shot 2020-03-24 at 3 32 40 PM" src="https://user-images.githubusercontent.com/43067752/77468938-b54e4c80-6de4-11ea-947c-9276177dd1a0.png">

**Comment by thomasjbradley** [comment]
Did you connect that real domain? The `artexpose.com` one?
