### ISSUE TITLE
Not being able to link my website

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/ecommerce-pattern-library#3]
Good morning @thomasjbradley

I am having issues with linking my website. I've tried to deploy many times and it fails. I dont know if I did something wrong.

<img width="1163" alt="Screen Shot 2020-03-28 at 11 46 42 AM" src="https://user-images.githubusercontent.com/43067752/77828725-99ec8580-70f3-11ea-9b02-c4f3e2dfefc6.png">

**Comment by thomasjbradley** [comment]
It mustn’t be working on your local computer either. What errors are you seeing in Terminal?

**Comment by dasi0075** [comment]
Hi @thomasjbradley here is what my terminal is showing

<img width="570" alt="Screen Shot 2020-03-29 at 1 08 31 PM" src="https://user-images.githubusercontent.com/43067752/77855435-6e829d00-71be-11ea-8aa7-872f250293ee.png">

**Comment by thomasjbradley** [comment]
I can’t figure that error out. Have you committed & pushed recently?

**Comment by dasi0075** [comment]
Just commit right now.

**Comment by thomasjbradley** [comment]
There’s a typo on this line:
https://github.com/dasi0075/ecommerce-pattern-library/blob/master/index.html#L5

Should be: `banners/banner`
