### ISSUE TITLE
Website Check Out and product card not showing up - Nadia

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/ecommerce-pattern-library#4]
Hi @thomasjbradley Opening this issue for you to check on my website.

Screenshots to follow:  
<img width="639" alt="Screen Shot 2020-04-05 at 11 31 56 AM" src="https://user-images.githubusercontent.com/43067752/78559455-67711580-77e2-11ea-8fc8-5a704a31e67a.png">
<img width="629" alt="Screen Shot 2020-04-05 at 11 32 07 AM" src="https://user-images.githubusercontent.com/43067752/78559458-68a24280-77e2-11ea-9339-5a465de5c2a5.png">
<img width="642" alt="Screen Shot 2020-04-05 at 11 32 18 AM" src="https://user-images.githubusercontent.com/43067752/78559459-693ad900-77e2-11ea-823b-7c5bfeb9e41e.png">
<img width="905" alt="Screen Shot 2020-04-05 at 11 32 36 AM" src="https://user-images.githubusercontent.com/43067752/78559463-69d36f80-77e2-11ea-8c65-2aeced8a7ab0.png">

![Screen Shot 2020-04-05 at 11 29 30 AM](https://user-images.githubusercontent.com/43067752/78559500-7952b880-77e2-11ea-8f48-4658ba16dd19.png)

Thank you

**Comment by thomasjbradley** [comment]
The `products` folder is missing an underscore (`_`) it should be `_products`.

**Comment by dasi0075** [comment]
My terminal now it's not working
<img width="573" alt="Screen Shot 2020-04-06 at 10 39 02 AM" src="https://user-images.githubusercontent.com/43067752/78570388-e9693a80-77f2-11ea-8871-ff84c2f14539.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
It’s the wrong folder. See at the top of the window it says, "nadiaotake", it should say "ecommerce-pattern-library".

Make sure you use "Open in Terminal" from within the GitHub Desktop app.

**Comment by dasi0075** [comment]
OK thank you,
