### ISSUE TITLE
Read.me Page and Favicons for Marks

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/ecommerce-pattern-library#6]
Hi @thomasjbradley

I don't know how we supposed to show you our progress for marks so I just finished today favicons and readme page updates. I have also added a bunch of other stuff but don't remember what I have shown you or not. 

![Screen Shot 2020-04-13 at 4 40 27 PM](https://user-images.githubusercontent.com/43067752/79159148-91f43d00-7da5-11ea-846e-4e956260bdd9.png)

![Screen Shot 2020-04-13 at 4 40 47 PM](https://user-images.githubusercontent.com/43067752/79159158-94ef2d80-7da5-11ea-8af3-274be406ed10.png)

**Comment by thomasjbradley** [comment]
🥇
